// <auto-generated />
namespace Repositorio.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_150_ADD_TABELA_EMPRESA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_150_ADD_TABELA_EMPRESA));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121458138_VERSAO_DB_1.5.0_ADD_TABELA_EMPRESA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
