// <auto-generated />
namespace Repositorio.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_132_REMOCAO_DOS_CAMPOS_DE_ACESSO_DESNECESSARIO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_132_REMOCAO_DOS_CAMPOS_DE_ACESSO_DESNECESSARIO));
        
        string IMigrationMetadata.Id
        {
            get { return "201711081628541_VERSAO_DB_1.3.2_REMOCAO_DOS_CAMPOS_DE_ACESSO_DESNECESSARIO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
