// <auto-generated />
namespace Repositorio.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VESA_DB_151_MODIFICADO_ABSTRACT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VESA_DB_151_MODIFICADO_ABSTRACT));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131143300_VESA_DB_1.5.1_MODIFICADO_ABSTRACT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
