// <auto-generated />
namespace Repositorio.DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VERSAO_DB_143_ALTERACAO_T02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VERSAO_DB_143_ALTERACAO_T02));
        
        string IMigrationMetadata.Id
        {
            get { return "201711171727201_VERSAO_DB_1.4.3_ALTERACAO_T02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
